#!/bin/bash
# Criando ambiente virtual e instalando dependências python
python3 -m venv beanalytics_venv
source beanalytics_venv/bin/activate
pip install -r requirements.txt
playwright install --with-deps chromium